### ISSUE TITLE
unable to see any error message

### ISSUE THREAD

**Issue by rnons** [cprussin/purescript-httpure#124] opened 2018-10-27 02:06 UTC
Hi, I'm trying to use httpure to write a simple backend. It's a bit strange when an error is thrown, there is no way to see it. I have a reproducible example: https://github.com/rnons/play-with-httpure/blob/error/src/Main.purs#L13

`curl http://127.0.0.1:8080` get
```
< HTTP/1.1 500 Internal Server Error
< Content-Length: 0
< Date: Sat, 27 Oct 2018 01:56:31 GMT
< Connection: keep-alive
<
* Connection #0 to host 127.0.0.1 left intact
```
 Open http://127.0.0.1:8080 in browser get
```
This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500
```

In the terminal where I run `node server.js`, there is nothing. There is no error message anywhere, which makes debugging a bit difficult.

**Comment by cprussin** [comment] 2018-10-27 02:50
Yeah, I'm tracking this with https://github.com/cprussin/purescript-httpure/issues/109, we currently don't have any handling for errors at all.  I've wanted to give the API more thought than just log the errors to the console--ideally I'd like to make the API catch errors and force consumers to write an error handler, possibly defaulting to returning a 500.  Any ideas here would be much appreciated as I haven't had the time to give this any love yet.

I'm going to close this ticket as it's a duplicate of #109 ; please continue the discussion there.

**Closed by cprussin** 2018-10-27 02:50 UTC

**Comment by cprussin** [comment] 2018-10-27 02:53
By the way, I'd be happy to accept a PR to just log the error out for now if you want to submit one, with the understanding that eventually we'll do something better about it.

**Comment by akheron** [comment] 2018-10-27 04:57
As described here, throwing JavaScript exceptions isn't a good way to implement control flow with ’Aff’: https://github.com/slamdata/purescript-aff/issues/136#issuecomment-356814485

If you want to implement a control flow with errors, the best way currently is `ExceptT`.

**Comment by cprussin** [comment] 2018-10-27 16:18
@akheron fwiw I think the example there was just to illustrate httpure's lack of exception handling; not an example of what should be done with `Aff`
